apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: database
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:1hRFoPItcCAv+qa77fDbC+P7Vw==,iv:QHiUN3i0ZeW5QQ9XRYmhFY+qLjYtKObjCVi+Y5UcOX8=,tag:4EhKxSTMTrgIjDvD0jSvAA==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:kRCOLc7K3hjYKAN2g6w4VR3ORRabNyU=,iv:uaScuIrNl9rIDzshayREreQeLmGJIXto2bMIbhhvFYw=,tag:ondOHMXb9KTVWMart6L6mA==,type:str]
  config_local.py: ENC[AES256_GCM,data:Bvvfs9YkX+fWDKiDVl3nqodu4whkfH2Y6FLzBTwMSq3c84od7sUOXMYTW7GLs3HG2wXXxrrrBMQkQSJvL3AItFqYiBfVJds5AWqqC5fNPqKAshdehV2Q7ZwKKPzsQ133lxNqtqFPF43vIgXmqk7SyUWSw20NOS2cfCwDGzsN2wsoywpYmRlzlUmMMBhcPe+s1cPglQgqZbR7PDtNi9w7FykUDWgsu3Cuy6SmxKarbVfIWX3hv5nSPF+ywOuIv3wKZRaW9ty3JMkxiI2aOGNSidph75ghtHcE+Y4As5QV9f2PZjkBZbBcGo1pTGjfM44stOU9c+dam3P1hDch6a1lryZMW930It/4SP98Xu9ACHVE8j6J+a4xUDcggkdueH0CaDIoz3M+X1CUwtcx9g8CJWp2n/Z3QrBq9R4qcyX2Iz3n9tUyv1Il2s2i+unj3//qDc45MctvsbKAYiLGw9WXewL7w9+Z4Ud8prlBt3kUb60TUc3xHxwNCKG+tw8z70jPtk12kpu1Jv7hG2sm4u/osyHDPSclc2caM5zgI3Dv52v2d9X2tI/YKjiiAl6/au8DpT4S2AHrNpyWj2e8plhwZfZ2u/m4noDpj8oC904DJZimmfQgEBw5ckDWlYZoSyE+vBYxMmQtQpvr2gIVCtuPtCGn200YW4Vp5bO9N1tmgzh0WePC10BDnfgU7c3yPFssTYwDxYvp/wDEMeDGSFBfYuvXu8HAZhOZU88XnKaQPZf9QEpKd7bh2B1dJJ5r9t/s6l1sKreI+5JnLLAvoCIQkI4oFDKQRVuN6kCmZn4doql6zAzkSjTCcfJ5LDMPF6hTLYSC1Jkuc8npaJ9/6ImtviIXRSMnDvXW5AlqEhTYO8lJMIBugGtW7Ggp6vRtFDGMe9ieF6UXH2R22Gl614f4ZJqWuIiVqr2Wf+vqavS3TcVwt5YR71m2+aKBqAnhj/VlzSTUhZeUBot+gnfiRGKJOwek5nJuRmkCYexH8kvrqt2eymkbCfnRLMNimv1R9Di09oViPuaw+NH15XRx8w6KQyE1tit7jUqhXVmeJxQyH2tX1Vi/5owPejOLz11EvIX//yTnHCyL81cR9fD3Eafq+nvu6jYOH2BcmF5TqC8j/fULdVu9cyFCF2rdsgDakkvGtww17uvLJ+RjG9sBKPU9Pid9jECi5hXl1bkIyBBDSRVFnH9IXOGDC3/IMYB+lKVf0qjf6IP1zFdsjpvbUL2VtKXYa4Fzj0XyvQkpaNIa5tdDo1N6bT2YILCVpt6DWjTluo8cXCT/9l3ylm6Ypg==,iv:9+8L3mui/MHWJhkpWryuEpu5qnvWOBvagHRyc1tzo+I=,tag:mFjUYniaot3eNyuPqxnwyA==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdXFzNnc3dGprZ3VVc2Zr
        S2NVS29mbEJlRDl0WGUrb3FweTYxamRJcERFCkdNakxIcWVIZHZ1MXFJSWVzVDJ1
        WEhGUUFlbCtycGxTYjBDdjI0RWtWdHMKLS0tIFZIK00xZTB3OGp3STUzY3VXTFhZ
        Q2h5TjYxQWN6a2pOWFdFNjJkMzhGNWcKTWsGZI2BDkde2mWkcNyc+jhVdldLSYXs
        4xakfj73KLpiIZ5DE7zP/9gEtH4MkuuM5uIXld/lKZXbT4gX1CDejg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T15:17:51Z"
  mac: ENC[AES256_GCM,data:liaKN1FztFgsFMkcKNITh/sM3YHCzugT/62bW9m0zPuBZgRYhjJ9ANptH5d7UfPGK5aWDoRee1+AaAobaI+SQOeufP9Cv1iLWQWeTf+x4JySW9P0cpuGVrV4D+Q77sFljXPUwxE6qpdWlqrQNYVs9wMvizKQvg/NGUYwZGz9aSI=,iv:vWYQi1mmWo1CQHPsQRfjWN9+oMEu+jxWXxfixrFt3zU=,tag:4sCYArfkeVSMOo4h/kLuHg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
