apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: kubernetes
  sources:
    - repoURL: https://github.com/mebezac/home-cluster.git
      path: kubernetes/apps/valkey/valkey
      targetRevision: main
      ref: valkey-repo
    - repoURL: ghcr.io/bjw-s-labs/helm
      chart: app-template
      targetRevision: 4.5.0
      helm:
        releaseName: valkey
        valueFiles:
          - $valkey-repo/kubernetes/apps/valkey/valkey/values.yaml
  destination:
    name: in-cluster
    namespace: valkey
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
