# This file will be encrypted with SOPS
# Run: sops --encrypt --age <age-public-key> gluetun-proxy-secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gluetun-proxy-secret
  namespace: gluetun-proxy
type: Opaque
stringData:
  OPENVPN_USER: ENC[AES256_GCM,data:C0JK7EsqEfyqwGchDSaPVQ==,iv:z72pBgz+dWziovxpgJZ9lifRSUyp8Xd64nSMzA4e30c=,tag:gCSp2t2jKwWx0JUHhPI2gA==,type:str]
  OPENVPN_PASSWORD: ENC[AES256_GCM,data:af/FvcLnqlWAwQ==,iv:c3v7SOcXIL0Yj3oHXrDf7k35tpGRnsh+SmUYZhXVZ7o=,tag:Q0BX3sGEDdkxNTjwuMhqIA==,type:str]
  OPENVPN_ENDPOINT_PORT: ENC[AES256_GCM,data:s/kN,iv:aagYjOuCEavHjQ3P8xP0ACGjZtMmMn9VTyuScHRMnvc=,tag:hr3GkFm5Jq/F8V9P9oeBxA==,type:str]
  HTTPPROXY_USER: ENC[AES256_GCM,data:1m0YjGPTqLqCXhIZMfZRpn8liQ==,iv:ooeRmnYA70K5kfNO+meJtVeuMYbKbgf1xLC4v54/LTk=,tag:usMjdO2MRf6Y/MGP3Ce9UQ==,type:str]
  HTTPPROXY_PASSWORD: ENC[AES256_GCM,data:c5SAwa3tTXO2Oi7h532Z1FryOLDQmPbW85Whnjirlg==,iv:AcVNJ4iR4U7RQP9LlxUoiKMddw/ux+00Lp0sWjAZclo=,tag:S8GN1lWqk+rSNg78bgAhjQ==,type:str]
  HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE: ENC[AES256_GCM,data:7w1oLHG+S3vtA1O/eTOl,iv:ArFJkkqtb4Ot3ZwZjcEAngYHfO4MQEPBwV7Ysr0VpBI=,tag:6zCNLZ9kt8umeYDQjUTy1w==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSU0xbG4wYUk2dmFIOHNx
        d29YZ1RaRzVobXk5RVJ2TmY2YjJzMTB4Mm00CmIraGRCYlRyQ3RETldTMC9GUklt
        dTRCcDMzSVY0cWxZVkVuUDFJZjcvSTQKLS0tIENSd2gzWG1UY3AvSUhncHJ1aFVS
        ejNmOCtBeXlydy9QZURUbDgySzV0LzgKERZV4n/5GW0cBXZid1vEGo4WdOgZXWV0
        +woOlqKUS7MR4SUBeJDdzNzi/XozZMJd09Yyx8XTRx5GA1vEH3ipyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T22:51:10Z"
  mac: ENC[AES256_GCM,data:Hxo962V/fbt2JQquZsyA9+eHRdQQYhP8FC9sfe/SSmkreAycHNCe3TYOj756/VFkNqfpTR9ZPEoXs4vnDGt3hRLMNRiFhybpg6z5IrmGEPeghLZ6FFJyQxRwUu+KedbG0TZy6e9G8ZYz7xppgC83svKxx9gTxelyW6HPTktzkFY=,iv:eGyhCzocohIn9b0Wl7bpfUGhv5SP8rWEKSA7DDndTCQ=,tag:L4bWnBaW/Rw7SoAnMhDj3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
