# This file will be encrypted with SOPS
# Run: sops --encrypt --age <age-public-key> gluetun-proxy-secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gluetun-proxy-secret
  namespace: gluetun-proxy
type: Opaque
stringData:
  OPENVPN_USER: ENC[AES256_GCM,data:C0JK7EsqEfyqwGchDSaPVQ==,iv:z72pBgz+dWziovxpgJZ9lifRSUyp8Xd64nSMzA4e30c=,tag:gCSp2t2jKwWx0JUHhPI2gA==,type:str]
  OPENVPN_PASSWORD: ENC[AES256_GCM,data:af/FvcLnqlWAwQ==,iv:c3v7SOcXIL0Yj3oHXrDf7k35tpGRnsh+SmUYZhXVZ7o=,tag:Q0BX3sGEDdkxNTjwuMhqIA==,type:str]
  HTTPPROXY_USER: ENC[AES256_GCM,data:1m0YjGPTqLqCXhIZMfZRpn8liQ==,iv:ooeRmnYA70K5kfNO+meJtVeuMYbKbgf1xLC4v54/LTk=,tag:usMjdO2MRf6Y/MGP3Ce9UQ==,type:str]
  HTTPPROXY_PASSWORD: ENC[AES256_GCM,data:c5SAwa3tTXO2Oi7h532Z1FryOLDQmPbW85Whnjirlg==,iv:AcVNJ4iR4U7RQP9LlxUoiKMddw/ux+00Lp0sWjAZclo=,tag:S8GN1lWqk+rSNg78bgAhjQ==,type:str]
  HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE: ENC[AES256_GCM,data:7w1oLHG+S3vtA1O/eTOl,iv:ArFJkkqtb4Ot3ZwZjcEAngYHfO4MQEPBwV7Ysr0VpBI=,tag:6zCNLZ9kt8umeYDQjUTy1w==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSU0xbG4wYUk2dmFIOHNx
        d29YZ1RaRzVobXk5RVJ2TmY2YjJzMTB4Mm00CmIraGRCYlRyQ3RETldTMC9GUklt
        dTRCcDMzSVY0cWxZVkVuUDFJZjcvSTQKLS0tIENSd2gzWG1UY3AvSUhncHJ1aFVS
        ejNmOCtBeXlydy9QZURUbDgySzV0LzgKERZV4n/5GW0cBXZid1vEGo4WdOgZXWV0
        +woOlqKUS7MR4SUBeJDdzNzi/XozZMJd09Yyx8XTRx5GA1vEH3ipyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T22:09:54Z"
  mac: ENC[AES256_GCM,data:DQ45LtpYcwA80I6NojepFCqipkQNXEpnDsJd/gjyoy212mw7gi3iBULsKmXPIcarUjz7zHclVoyYg1sSriB0bd94wMzpkr8n3xULIdgioAWzB/Z9UOOw/m96pU8rfUhob5rDRixyGz25ZV+S5NR+CjLEvNoa0+rFqoTiFZhCB+g=,iv:eZDj7vj+lR1u7ve3Xhqu6mqC3k2QVf2/vaAec+33+Ng=,tag:XkcQljlihilBWcmdMi6iDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
