# This file will be encrypted with SOPS
# Run: sops --encrypt --age <age-public-key> gluetun-proxy-secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: gluetun-proxy-secret
    namespace: gluetun-proxy
type: Opaque
stringData:
    OPENVPN_USER: Windscribe-username
    OPENVPN_PASSWORD: Windscribe-password
    HTTPPROXY_USER: proxy-username
    HTTPPROXY_PASSWORD: proxy-password
    Windscribe_REGION: New York
