apiVersion: v1
kind: Secret
metadata:
  name: podly-secret
  namespace: podcasts
stringData:
  PODLY_ADMIN_USERNAME: ENC[AES256_GCM,data:bkQR,iv:YdRn6bYS/U9x1VgaS5tNhlfms01/y3AIYHKZBD5RVOY=,tag:8seBUWkbgzjKLBAwWktTvQ==,type:str]
  PODLY_ADMIN_PASSWORD: ENC[AES256_GCM,data:u75ZWfCbTzc7e6VBGl4F50pIUvWMtGP96A==,iv:YL5ZUbRDtcNAlsplDpGOw3Tx7GhS9uZ4JKtn6GxtSZQ=,tag:2VIkCxXBi6sld9ewf6n6/w==,type:str]
  PODLY_SECRET_KEY: ENC[AES256_GCM,data:EweswMU7/LXiGtRCPGLkqV9M+/7r631ocbIj3JWI1DMcRhYTwQHBt+cfcp3ahBkpoaYdnssJOYX793MxMW+TEA==,iv:bvklEyLBBO0CnZ4uuDFG08LQYy/hqKyWXpxzfBegtoo=,tag:uCA05F9vD8n70QsM8HQURw==,type:str]
  GROQ_API_KEY: ENC[AES256_GCM,data:XWFa6+E2MDoGL/tI1ihYOnPIhp6/eWKY7QUheGauDouev5rgISqb3s6CAMgOoU25pKZ0WDmnFac=,iv:Oi7+62b/DEAustxa3x+JGujDJUqSBBsrhqZ9JCH4NqI=,tag://pgVQBWJ5L4uCWQ9Rgxbg==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOd3UyYXZEQzM0SGhwSjQr
        dTdORmpiSFZMRGsyOUMwQStzbzRpOG5OL1RjCjdhck9rM2RWVEk2OGNsYndrR2dn
        Q1A2ZzhFSmFHakwwTmxEaWdjdi80YjgKLS0tIGF2REZrU2wvQ3RIOGxPNUxYQ1Y1
        UVVIWmhvNlUrNjMzWmRCWDE2enZjdjAKGAS/kqe+NoPAA/BajEhjCCTrbIb23xhy
        H4MRxIRbbWTtR213Jl4MH4PNDLlC2pgqNXeskD6mgs5jZs2CTwn0LA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T22:10:55Z"
  mac: ENC[AES256_GCM,data:jYxeyuuNnKqS+Zgz7f/aKLSj1xBwlpn7dLWDWUP9XFrG64w+fDb4e0X/lm0VTJ34uTyi1YP+mzLcf+24ldaiafObtHGhghp80YRUoSc+16YFvtUUaOJ+gLpWPL+nLGX1n3Ui9K41UVhLMYkaRlSKloR1PMTdOxDd6YW5LGs0cIo=,iv:8/2wwOoUXbIn6z0LE5vC2sclOq+zg1a2hK/m5lQmQuc=,tag:D6V5bHjLrlOx8iLgJOKzGw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
