apiVersion: v1
kind: Secret
metadata:
  name: podly-secret
  namespace: podcasts
stringData:
  REQUIRE_AUTH: ENC[AES256_GCM,data:/wSmvw==,iv:lCVpgYPVL869LN1Dbkg4bkqwauveCsJppz8mvlQpzlc=,tag:ezezeXr+FESP1zrtswEq1w==,type:str]
  PODLY_ADMIN_USERNAME: ENC[AES256_GCM,data:bkQR,iv:YdRn6bYS/U9x1VgaS5tNhlfms01/y3AIYHKZBD5RVOY=,tag:8seBUWkbgzjKLBAwWktTvQ==,type:str]
  PODLY_ADMIN_PASSWORD: ENC[AES256_GCM,data:u75ZWfCbTzc7e6VBGl4F50pIUvWMtGP96A==,iv:YL5ZUbRDtcNAlsplDpGOw3Tx7GhS9uZ4JKtn6GxtSZQ=,tag:2VIkCxXBi6sld9ewf6n6/w==,type:str]
  PODLY_SECRET_KEY: ENC[AES256_GCM,data:EweswMU7/LXiGtRCPGLkqV9M+/7r631ocbIj3JWI1DMcRhYTwQHBt+cfcp3ahBkpoaYdnssJOYX793MxMW+TEA==,iv:bvklEyLBBO0CnZ4uuDFG08LQYy/hqKyWXpxzfBegtoo=,tag:uCA05F9vD8n70QsM8HQURw==,type:str]
  GROQ_API_KEY: ENC[AES256_GCM,data:XWFa6+E2MDoGL/tI1ihYOnPIhp6/eWKY7QUheGauDouev5rgISqb3s6CAMgOoU25pKZ0WDmnFac=,iv:Oi7+62b/DEAustxa3x+JGujDJUqSBBsrhqZ9JCH4NqI=,tag://pgVQBWJ5L4uCWQ9Rgxbg==,type:str]
  LLM_API_KEY: ENC[AES256_GCM,data:Iz0/+oJD9XAiUeAn0rlwu3TnyMxJokX74k9eJGx8Oh3SzJC21FF1uBe4A7fV17WEsRYtEDTxJVULgvWBIk0nMf2FGAIPRocGuw==,iv:JVUeiah/fXPpNQA+0oJs7c4MA8mMB225I1Tdbcjw1UA=,tag:itDp0G/FerqDIznIL2B6Iw==,type:str]
  LLM_MODEL: ENC[AES256_GCM,data:5nndCMcYqNJNnq8Yl088UjVMZQgMyVvoBiWXqBSSomv29yKHBpdeUKy79nHc,iv:IvrslQHUCf7MMYhM3PvPbctYaJFyF+LoXuVUtIxH/Oo=,tag:hvv2lBUfCoBdW6LeAD0k1A==,type:str]
  OPENAI_BASE_URL: ENC[AES256_GCM,data:SI/L63FOJ/pUVFc+ZekeOH87pB68Sb/LLp4BpQ==,iv:lKWCUqGn/cnjYm7U9ma7pKkzELqGkIkI830D+6erY9U=,tag:QtRNgtybzqOyXUQ0lPMmyQ==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOd3UyYXZEQzM0SGhwSjQr
        dTdORmpiSFZMRGsyOUMwQStzbzRpOG5OL1RjCjdhck9rM2RWVEk2OGNsYndrR2dn
        Q1A2ZzhFSmFHakwwTmxEaWdjdi80YjgKLS0tIGF2REZrU2wvQ3RIOGxPNUxYQ1Y1
        UVVIWmhvNlUrNjMzWmRCWDE2enZjdjAKGAS/kqe+NoPAA/BajEhjCCTrbIb23xhy
        H4MRxIRbbWTtR213Jl4MH4PNDLlC2pgqNXeskD6mgs5jZs2CTwn0LA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-04T15:10:52Z"
  mac: ENC[AES256_GCM,data:8f7pC+yPuYf53SwLoZu5tvEImMT2nqRReDndLM7VAzcay1xVcRjYnOVFrd7yfq+Brj7/Ua0wocGNHkaD+fAIiuwucddbiiWtbZo/J6O8tNgN0W8K+maZ2fPWyNzOcogUo3cLKsiFcPQkTt7EwDfRh0MeymzNII0jDjkxTyOmiso=,iv:6qR1D3RvTbU2gYGq6LDDx3YXi8E8maz7QkH5JVYwf24=,tag:SWEUuonhrekUGmZnvs0lZQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
