apiVersion: v1
kind: Secret
metadata:
  name: podly-secret
  namespace: podcasts
stringData:
  REQUIRE_AUTH: ENC[AES256_GCM,data:/wSmvw==,iv:lCVpgYPVL869LN1Dbkg4bkqwauveCsJppz8mvlQpzlc=,tag:ezezeXr+FESP1zrtswEq1w==,type:str]
  PODLY_ADMIN_USERNAME: ENC[AES256_GCM,data:bkQR,iv:YdRn6bYS/U9x1VgaS5tNhlfms01/y3AIYHKZBD5RVOY=,tag:8seBUWkbgzjKLBAwWktTvQ==,type:str]
  PODLY_ADMIN_PASSWORD: ENC[AES256_GCM,data:u75ZWfCbTzc7e6VBGl4F50pIUvWMtGP96A==,iv:YL5ZUbRDtcNAlsplDpGOw3Tx7GhS9uZ4JKtn6GxtSZQ=,tag:2VIkCxXBi6sld9ewf6n6/w==,type:str]
  PODLY_SECRET_KEY: ENC[AES256_GCM,data:EweswMU7/LXiGtRCPGLkqV9M+/7r631ocbIj3JWI1DMcRhYTwQHBt+cfcp3ahBkpoaYdnssJOYX793MxMW+TEA==,iv:bvklEyLBBO0CnZ4uuDFG08LQYy/hqKyWXpxzfBegtoo=,tag:uCA05F9vD8n70QsM8HQURw==,type:str]
  GROQ_API_KEY: ENC[AES256_GCM,data:XWFa6+E2MDoGL/tI1ihYOnPIhp6/eWKY7QUheGauDouev5rgISqb3s6CAMgOoU25pKZ0WDmnFac=,iv:Oi7+62b/DEAustxa3x+JGujDJUqSBBsrhqZ9JCH4NqI=,tag://pgVQBWJ5L4uCWQ9Rgxbg==,type:str]
  #ENC[AES256_GCM,data:KDVvnyd299it92sh8EiVwZk65Dfrm09lUAwn3QdZlH0fgpGWKkvXtRZUBbI1ImyM5uGaUbSIIdK39IJwCjuowpwBNpYFXoPvuGP1sgjNwm0688MAjmp8Jhq1oyRdgQtbIQSMAZ6DrR2TuZHeNTIXcxfjVlQ+ouXFor8=,iv:N/6B0Xup/Mbo2r2rVaYEf67YkhP3iCC/u2LhCtl4yKo=,tag:a9gYeyaenC6oSGFvmSsWuQ==,type:comment]
  LLM_MODEL: ENC[AES256_GCM,data:5nndCMcYqNJNnq8Yl088UjVMZQgMyVvoBiWXqBSSomv29yKHBpdeUKy79nHc,iv:IvrslQHUCf7MMYhM3PvPbctYaJFyF+LoXuVUtIxH/Oo=,tag:hvv2lBUfCoBdW6LeAD0k1A==,type:str]
  OPENAI_BASE_URL: ENC[AES256_GCM,data:SI/L63FOJ/pUVFc+ZekeOH87pB68Sb/LLp4BpQ==,iv:lKWCUqGn/cnjYm7U9ma7pKkzELqGkIkI830D+6erY9U=,tag:QtRNgtybzqOyXUQ0lPMmyQ==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOd3UyYXZEQzM0SGhwSjQr
        dTdORmpiSFZMRGsyOUMwQStzbzRpOG5OL1RjCjdhck9rM2RWVEk2OGNsYndrR2dn
        Q1A2ZzhFSmFHakwwTmxEaWdjdi80YjgKLS0tIGF2REZrU2wvQ3RIOGxPNUxYQ1Y1
        UVVIWmhvNlUrNjMzWmRCWDE2enZjdjAKGAS/kqe+NoPAA/BajEhjCCTrbIb23xhy
        H4MRxIRbbWTtR213Jl4MH4PNDLlC2pgqNXeskD6mgs5jZs2CTwn0LA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T15:36:15Z"
  mac: ENC[AES256_GCM,data:hPT1MJllPhsIpyatmj+Ib1H2GBO2u5GDueN+Hkq+YEVEiP3PUo6DJnDgYT2krQLrU/5tEy13YIhsFVsupa538wGoz6NeQiLc036Dv08xJwFafyYopyrIAfj53WAvO3p/rpSWyWzdx0ElBhYm+UdbrfwoGBqHzMXU/73+OuLHYq4=,iv:yhnn09IuYuo3bnR5EIOoCPfv9JT2oDST56f7WofSL5Y=,tag:Y172WJFbeA7oU3v0fWcPQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
