apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: pcab
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:NeAbtJM8Vo8EA73UzawmLnQDKPTeV5+o/YR+3D8Q93ksvH8wQ1Tgn9uw6nyV00jTMkwQlSoL0ZOKkA5vn2UEveJPcHCFnfFKVPGJtbAbNVved0VqhgBmyfxSZeq2wV8S/pud3G7+uzyfHEFumCx1JP0Xx0tIxNCQNOTQXgmSoFRXh/c/RstLiBRZPCfNLSVyXzFhd5+Yst6eP6vm1tv/hETDXTASQElcU5vmR6C6BuTPSn9VlTCP2AORS1IctJL/C5xliY92F+iTMyy9PPJ4a2lYa5VzFRMu,iv:NNWtlIvFmLdGzJUX5utYasauC/22cx6U3+tzs/uy0cU=,tag:zddO5qzNkyiir/PKLhpoww==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVkJZS1pCVFdlbVJBWlp5
        blVROHhXdXNOTHcxNkQ4Rzl6RldVZGVPeFJJCndYd3JoZmJDajdweTBtMklkMzA5
        TS9oMnNTYytXL2ozSTVLYjU1ZWZWQWcKLS0tIEJJMWV2cC9JRkhSRWF5dS8vaXlr
        a1EyZTN5dHdnalM2N0lyMWlhR0U0ZncKtPqvp/1Mm7NUfoeab8qVdjKO6mOxK3E3
        vAYzDocDtMHk2iZTZ3cJIoNgVmE6V2BEpk1vJ5TBLGfr9CPvV32GNw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T22:38:04Z"
  mac: ENC[AES256_GCM,data:CG5kfnnZp09CPCbmjnhBjjFjZSKYsVnjdVGLp+/vPkA6Yg86OzCTLMYIiZyTsU0w/fexV/vgry0+u0lx0imIShW3edsH7dD48+U8yEI7dSU37mericzPYWrt83mMJPoGCU7SQoMLoJkIpaGuh3taQrw5QypC4ERqeRLi/ieeyUU=,iv:I17V/AK9EsfrtKJqszrsgfXk1bRMN3ah1pe3g0m3IvQ=,tag:yk++SuUGzLWCEcW597TlGQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
