apiVersion: v1
kind: Secret
metadata:
  name: pcab-secret
  namespace: pcab
type: Opaque
stringData:
  #ENC[AES256_GCM,data:rFbbYomKlow78Ye5XkcHHZWFdwUPm9qYXPCKEA==,iv:fOb9O5N7xzFcqgCRBR9O+E77P5VoxJZwaQc5iZcWJok=,tag:fJfM/5BnVZO9f0vNq+bTrQ==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ALjHkw==,iv:pCGPbfv5KRAv3ByF104SxxiZ5vbhoaoPxv699S0kdak=,tag:RB6KmHczRJgaE7ukvC7QNg==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:9W7lDl5uF8XelKFyBvudf92l/5+lwINz3PUoMXQltriXqyJzBm94fCvd5Ybnv8nc+w==,iv:VptgGe6DDixl90zlYQ8Enzo2mk6V8LHt56l/srl4vwE=,tag:Qh8PFV6rnCAbh8pqPazPRg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:vRtB7Q==,iv:iYCgyCnIuhO/Az68P/BknJqBLI5mgcdBB3CQ5gospQg=,tag:0sl84AUuOHTlo6P+vhCrtQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:4noDjs8LvAnonpcFaFSwv6fj9+J6O6n0zwv8Zg==,iv:WkcvOjx/MpgJeRqL9893dV4qV2Vv1Jm9vjRrJLnSUDw=,tag:A+fY8MQhwULgl9UgOF+ZRw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:EQInfptcIaBhEqEumceY6l4gohLUbZ2GJWA=,iv:RZfRMEhb+cFn0k3Qy8+gQziBIBQdjM5HQbmXKW2JwUo=,tag:P2hC3nAdJrzps2BYQ2qnKA==,type:str]
  #ENC[AES256_GCM,data:O+LwA8qT1nZlqxQicftZQWBUomxMwPrlExCj6PKipps0DyC1nqrCY/fZ4Zi7JhRvdGZ9eBGeNgLPSagkWas=,iv:6Fr3W7DWIy+do0hUXjjPMAShjEBcezoPij/bPAukZhM=,tag:ZKw2i/GBDV6sNhA0gZT4tg==,type:comment]
  SECRET_KEY_BASE: ENC[AES256_GCM,data:FQwc9ZeKv3NlN9zz4jeBRxwVpJ4o9gNRqTtdd+mdZ5cuRwXEbqVGgV0yCWRFdSCHDzVXicQnu9bDJx49uhZtrg==,iv:VXPhUdPlDgEWAiCDznyd+52y8XGLz86qLEdU45u9NQ8=,tag:OZCn0q9fy+sZOFbYbW6abQ==,type:str]
  #ENC[AES256_GCM,data:mpLUgpX/VS2Haj9BwDDJG5HFTlWGZHk=,iv:qub5hs3Y6llj2tSpOu/pyaGt2rEaugzYsbM//ZdtYCQ=,tag:z72/4DBrVs7V6z9fakBnSw==,type:comment]
  DATABASE_URL: ENC[AES256_GCM,data:U+L2P0O2wm8ixTKXi0tsE0bnaWmPluAR0LQZGvZ4/51krM4Zc0Kug5PFUS8Sx8Wbn6kJjTZwbMw5pb/AKajukyP64T+WyVp4efdiX3rfOAMpKLUlqQBa0Q4KyWQpsbb1GqaetEtuaaU=,iv:GMCoOW2khOKYCE0wbktoYr40d6cpPGkBDM9bKDHguew=,tag:ZWvUMSs6rJMs+cQmXM3PRA==,type:str]
  #ENC[AES256_GCM,data:Tg429cRRseI97Mm5mC7Bkr/DWOt+sPVvmJvS/tyAVlUFLLw=,iv:KQAEhyxdY7QbQ/RkqRSgSnFIEC2FHO/Q9425ENLjzYY=,tag:fa+UkeYZnVIz55o/83Kvjw==,type:comment]
  GROQ_API_KEY: ENC[AES256_GCM,data:5KPO9gzPeLB0EA06FMVFZuohTTwXxjme49Vu+fwv8jPCiC29g5zTQhlMYn/L07VXdFFqb8e0Dzk=,iv:HV4GROp9uQ0Wf7iymMIvex+i3Qg71BrFBgGkTamNBm0=,tag:Al5ZNdCT7eyS7KfSjNVxqw==,type:str]
  #ENC[AES256_GCM,data:xDdL3IwjDMNOyh6iqXf9AkxgcO6Pptov8HMP7Z6PAL3IXtV9mGeZBe/s9TQ=,iv:4rhw6REgolT2Gw80uOpxh7BbBoFyN5SpsC0QMA4KgjA=,tag:pX8mbv8HyfMVxjuBmPcnHQ==,type:comment]
  AI_ENDPOINT: ENC[AES256_GCM,data:NM+KNi6LvBx5pQ67ABKbfQPyvPpRmuIOZixEjEZm4DXBoMA=,iv:A1IJmj+Rn3VRhCQTDUuOXBzHKnVAZYddK/gAbkxZ+YI=,tag:NFLe51ttjH/lRkVpvU8g5A==,type:str]
  AI_API_KEY: ENC[AES256_GCM,data:/BjAnWNEFpPWRIokisK1LntVkZYBhLi28AAbs1AtmixX22cI,iv:CtJK9cLWebMv1JRGc35TekaE4ZJfSrCCqfzDjHdfL0s=,tag:8b49sAOdNsPpELBFR0+RSA==,type:str]
  AI_MODEL: ENC[AES256_GCM,data:XMYhZPxlgtotFc98NYK2WfCGg8dyROLBzQ==,iv:iJL0F3vTXn9OXjJ1NlLM1BBP+fRW/KPGex45D8XISow=,tag:Na0NdywM/a2IwVgrxUl5SQ==,type:str]
  PODCAST_INDEX_API_KEY: ENC[AES256_GCM,data:SnBvhqj5TiyJV3gUT5sBjXQO8fM=,iv:6Rx3utog5Y8we+xjGBk5Oo+fTs4QMuVSx2MHfMX6CaM=,tag:YCn6SJJU6rqBMfzWqg0l3A==,type:str]
  PODCAST_INDEX_API_SECRET: ENC[AES256_GCM,data:nw8UTnukfgXCzfxJ5PaihfPKEWgWNMKVJwTTrshg5poYeKvQdo6GUw==,iv:RyUtASF5/YkajhMqWvibunxp7r33e+Z2tJxowbUSmko=,tag:9Kn9KmyMOH3L4dXoKjIVOQ==,type:str]
  #ENC[AES256_GCM,data:saiNOWqpNvm7cC9NPZkUsdMr,iv:NpH+gxnHcqFjxfoi5kv9FkdWHBuan+pbp6sY4zdBfaU=,tag:K9j9DnCwVCPCmG4zJyZb0Q==,type:comment]
  STORAGE_PATH: ENC[AES256_GCM,data:VIYXfpy7Uje44wpymKPzCFE=,iv:ZdusCtqV40qKWmbmlUhSb8TrOp9Y5pR0noSsExRe2ts=,tag:FaEpStB2B6y+CXumxdPDXA==,type:str]
  #ENC[AES256_GCM,data:B02G0Xc+vWcmgT5AFb28BJ+ojbwJ4J5DmaPRW4B2,iv:I3NqpBdB5wtDV/1J2ephgddOI+mSRQGiynhSXq5azbw=,tag:0j1tG05HowEWmPIE65nnrw==,type:comment]
  OIDC_ENABLED: ENC[AES256_GCM,data:z0FsJg==,iv:9Q/9xd7WyJcWN/Wm2l9FnqoLaJNS9wgV3TN6H63CMBM=,tag:OfGhkNMR0XJNZPcnsqMI9Q==,type:str]
  OIDC_ISSUER: ENC[AES256_GCM,data:XsgtHYLXbsKrGpUR4Ys9c5q16j+I1k+1tH4MZbA=,iv:kQ1J9UOF/VmVgx7+RSFc3RRpUTUEeUVyLcE36WPpBLA=,tag:ifUBU76dQRgsCeo1Y7YUVQ==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:G4u2qf/XU33C3fo7aVpKGkb/d4YXaMnX+FQnjbW0pKDwYR6p6UeyDeQIeWlvOhgl0bk8Mx543S132c+JX9tN2Z5ruQ0rMHAW,iv:jug8HMFnq+FUVk3npVbTPyFYVXsHTmwi2z6no6bXCSM=,tag:udPavnNdXAUgigTvaOfPqQ==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:f6N4371yCZ0yH0k/4tBkOhHAVc53/SDQbSyP1ikhf7JM9XbWF2hMklRdDuaUgGB+LHcLzU3DjgtIiv1ZiIrCE5ZjNZxjTYfz,iv:QKvW1YH4/0/yXGz7ZUEjbez7I5pktr4bbzifw+uy2Fs=,tag:vjt/JJc0fQbp4SkgaedMXg==,type:str]
  OIDC_REDIRECT_URI: ENC[AES256_GCM,data:cxQN1/1+zIsVrbMAa1dZVy96A731XfQ9zXM+Pnzuck1Z98vKPuRabpGhrpbgEeM=,iv:kPd1l7AbZ1+0HbZmEooOF3Hjk+T3zn8RirzGc66KnRA=,tag:UQnVor7yzJyLxzoTpTQAgg==,type:str]
  OIDC_SCOPES: ENC[AES256_GCM,data:D4eEsj2MNjHPF9S6jdeOXR5JjHE=,iv:pBqKbzL7PIsUgK1kQ7o/SWsfEDtZomtsaWtrettOdPo=,tag:0usAGZrvyO0Uyg5G8RDyRw==,type:str]
  OIDC_PKCE: ENC[AES256_GCM,data:RS+8lg==,iv:cr0qOKJVgaGXyzpxREVZLzR4AlkD/eiePqqcQH3ukE0=,tag:74JZ8Lvj4xiBfODIbRFN6Q==,type:str]
  OIDC_AUTH_METHOD: ENC[AES256_GCM,data:UnWp+BYT4UMQvMBoQa1cvXVcDg==,iv:B938GzXX7XfOPQ2NlxitDRFiVi7PHLLyDTumUTbyOHg=,tag:g0NXf8Mq+rnz5e2cbCERCg==,type:str]
  OIDC_USE_PAR: ENC[AES256_GCM,data:TYv+FVE=,iv:Zcttxe+7eQtxhwirIkif9eBqsfOTyW6d5oxENzZBzns=,tag:KsE+gTR/y94gCrb++p8nmw==,type:str]
  #ENC[AES256_GCM,data:UPO4bB57RZcOAECDi2odvYN6F0g9hiYxSCmIhTjluxXO4IwZG4Qgzy8qj5urVTmRoMM=,iv:1Kj3JeutsJ14us5O2O/e9Ue4s5cgqRWDwvP+KM61ECY=,tag:AD9nfi8+HFHmrJQN3R8BTQ==,type:comment]
  PHX_HOST: ENC[AES256_GCM,data:kMULVQ69HH1+1BWvebepZEaKZ4Q=,iv:JyhrYQGlElc0/5A3C4N+/lu1soHlUGc3l8et3TtVKVs=,tag:1Die9OIjRw3Qnqa28ZwLIw==,type:str]
  PHX_SCHEME: ENC[AES256_GCM,data:6CjpW2M=,iv:lgKoh08mPyYciw0tdtXkGLkMH17NP5Es/uOK0Jqvv5Q=,tag:Mtu7jIvAEOT2NtBpzPiv8Q==,type:str]
  PHX_PORT: ENC[AES256_GCM,data:MV+C,iv:CO52sB6bDMTG7RC42eKyIdCwaWIpfR/KIh9s6gyh1Cw=,tag:Irdgu3iGczA6vwp2KpAxMg==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxb2U0bmdsOTVhdUk0Sk9C
        S2VHWEp6VDZHd2dRN2c1SzJEamlTNFRrZXpjCm03RXgzN3hNOEp3Z0J6T0wyVlho
        Z1RQS3FiOHhQZVY4bCtvNVNMRmt4aUkKLS0tIFZXYmx4Zi9yMmZjUnhYcFhlNndB
        akNHclFCb08wWVJxVEJjcjhjV0tzUVUKKr3bvMticlrqISqFyzKGWJn6C08l37US
        Yf1rBVZxXmNU7cGQXWQjaZeYsSQ2Huhua3qckKB1jJUWdnfcQq42qQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T17:31:09Z"
  mac: ENC[AES256_GCM,data:6mnpEY53++y6gbVhcuWoVrG/RFGU9876oLvMH+DIgAoDeYOMLijSYBK81a0uNUNQ1kdL7p04O8782uauC875Jl5dCerNCxk68kZe16cjts4VZY1oBjmieD02Vk2ZYcWgvDfRH+9wJb1f8JLt92rkvrqkSBn7nE1HEtk4sUMfTsg=,iv:rhnnZwfE0y7+eha+3g6Ozx9mRQJxcXafHWZZLQSK+4o=,tag:Ho2v5CSL8vqmocGzcatF6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
