apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: pcab-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./pcab-secret.sops.yaml
  - ./ghcr-secret.sops.yaml
