apiVersion: v1
kind: Secret
metadata:
  name: lychee-secret
  namespace: lychee
type: Opaque
stringData:
  #ENC[AES256_GCM,data:mHPYgNPUiMs=,iv:ibJ5NZw4+OW9IXAjhemD6nT3koYYpRH1qWEvWbz8HVQ=,tag:xbko/JOKABvW7pY32bOFXA==,type:comment]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:w9lCAmUD,iv:8wXSNJRfDUy6ewwR7VtlvLsX42eJqS2sMCYwhm/xG2s=,tag:nFhApAsbkFRb1Zs1iHLIhQ==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:3DEKQvfAsnecnZY7pn990/zOWed20NWoo5uE6TCThJTBOBq9zBSQL4R5boF5ELLl7w==,iv:0gc88UJyrpMUxodFKnHq+m4xdiW+/Xu6E2MT3UmKxeE=,tag:n/KwGaUqV2cpuG5C0Cg8IQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:RX+pG43c,iv:qkq3ajxfVVxVQ2s9yHUW1/l5fBnFEZ9tYSFlQj1rdqc=,tag:GJ4AyQHFAzvPwtt8s5K1NA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:qpJ1X6yQlRU664b998luRqqyIOPNR0UH1c0Cwpk=,iv:UCgRLxmJPLzMnuB/k813vlPzrYvU1VPLBRBEoBvF/8w=,tag:QKBdgqGVOFbX1Wq8c9aZyA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:JlR1R8c/MvW6FIoxJSa+QcEluismfZnuZNc=,iv:HYiZqpfL1hRqZG0t8Qs7a+PV7GUQ+zIoATEhrSMRy0Q=,tag:zxyW5pDe5qskzyMDjGcfxg==,type:str]
  #ENC[AES256_GCM,data:deFPtPEmMQ==,iv:xwm6TlHyD5GqgVpLoeR2Fg3vNUmwbZ62qkXrLJeKKGE=,tag:JlCRwD5siL0s8OxbMK4NOQ==,type:comment]
  APP_KEY: ENC[AES256_GCM,data:pLqUe5M1+jhYTIhvWrYIxa+SpnRs/XLE3uxA4VpTwdf/bRwEvdSt3gWv3vhcIudw8S/g,iv:eV03fZsh/TvfqqpUd8GkI94U2IxGoQC49DIj6UaLVoQ=,tag:2Op0FMz3Oa+ZsozTX6ZTkw==,type:str]
  DB_HOST: ENC[AES256_GCM,data:pQ0SnnMmQKjSkp+GNbJ+PVNMDrC19zh6B7UNsIKeUTKnA6KHrCo3dDRKtfhBBuZavg==,iv:iXW5od5WmLzl/v0XGsNektHVxJEdc2/ekRZQfORH05Q=,tag:dEceGaVnwuyPWbyaI7kbyw==,type:str]
  DB_DATABASE: ENC[AES256_GCM,data:aDqC4pXV,iv:qHGGHygAuHUwqqSb0vtKKJdbhhV/JL5Tru9HTwpnE8w=,tag:tLDqebInUWeTpQYWxLoxpg==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:oOrgwTvz,iv:1UM2H/5njxeDfAlF0t6WJkMKI0iI26Q07TYDg2DBjdE=,tag:IItXBKh/D3rLUGDlJA0NhA==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:Fx43ugg8uW4sQQYDr3ILeZaeroIPL7o8IXfqjJ8=,iv:wT9haEiSdHZPMLqgP7sM6f0+VOXRzwOO5txQnmmSmJY=,tag:xrNp50tf5rm/8uGJEg10wQ==,type:str]
  REDIS_HOST: ENC[AES256_GCM,data:otK+gB3EUbncreIiFN+mSIEkgJVrC7Alx4agKwhbng==,iv:yEOyW3cvSyDeA3BDqz6DynClJCWDwzxW/e2oht9mMqc=,tag:JE6AGzbFIbdAHzZwX/jOJw==,type:str]
  REDIS_DB: ENC[AES256_GCM,data:xg==,iv:XzKgT07QAlzbDMZPugbLvnvHi1ADGzkWPBWgY+2/zME=,tag:tXe94T/HZW5N048HhKnIaQ==,type:str]
  REDIS_PASSWORD: ENC[AES256_GCM,data:hkbNLz99FCQQOdVWB1m+rUytlM869rI6FA==,iv:7i4umnjDofrd+vo85V7caHlzX752OsPN+HY4FKyWVN0=,tag:lqQKNVwnlqTO01m4v0ZhHg==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbFNKaWFkYnRxcnAyOFl6
        UDlRQUYvQkUwYlRWWWIydEJmdDFOK1QzQkI4CjYrSjFDSXRjUStqVEE0VDlHejhn
        d2F0eTlJVFI0dGlPRGZQbDFqVkdKY0kKLS0tIDlVZHoycTdDb2hsTTVNWXpnQmZv
        QlMzWDI4RE5sdHFJSjR4Q1p5bTlQcTgKEJpCYBDW2fFyO8FxRITlafFkJKpTX/Py
        h2KUx9mzzqs0YO1tTBoikriIJmUv9XX97+2aZAm7o+ycuKWXtdHuvw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T20:11:07Z"
  mac: ENC[AES256_GCM,data:qbaqGfIPqOOyColGMOcUMZJNSfSzKN/wCT/UvgyThMzvCHmNmcyem76Vi+PkDUQozOVamOYLJv4xfeBnmOW/OlurfRAw3AmM3OtV3txdPOv63rPGPWqi26HuAUFrL9XbFGDYwpd75mLMfxavvYJeNKZkUnoSa2UOy/jJj+0lvTo=,iv:SQnA6gOGOCzuVLibKpwu1H7HS+Sf1BfRqiM4VwspHpA=,tag:JBMqAet3GFJ4e1Mj+9NL6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
