apiVersion: v1
kind: Secret
metadata:
  name: opencode-manager-secret
  namespace: opencode-manager
stringData:
  VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:U5GX0TYHfvhTDWJlIUAdkKAz+30n5SzI6+7j90IBxarjcTYyK2bPRxM4o9T+guHxctLnM6i3AfHTCQB5crWla2wYsR0qpABDEQ5pnDhpO1/PEujxIX1s,iv:ZV9uBtiBwy59gen5oalq9oYh1jpS6HhYC/e+ma2byxw=,tag:2EGPEwJlg0R0DUlFpWcKTg==,type:str]
  VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:+d9WHCAGF/7x0w78rEAlvn5+Oe5UbV5Tt7JSY7cZC7H6wm8RgCPRestraQ==,iv:OYYEHZoUlcpFeg/NQrwor1tgu5iGqfRZJ/y/1CXf5uo=,tag:KiejUPbHxzqhe0KuL+jFrA==,type:str]
  VAPID_SUBJECT: ENC[AES256_GCM,data:kQ9QzQl2myNa2Rl3bv9CHfq28umX78UKTZyxdr+1yg==,iv:JjXxOMei4Tb6NjM7p6+4/xNkQEQ/QtRK2ysyecVPzDY=,tag:B6D+Wn594vgYIg/t6DieKw==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTEFsNStiTjlybHpHanN6
        NzVjUTBkM2htSUJRZUd1cXZQMWJEU3dzOFVFCm9JRXBuL2UxSEQ2TkcwRTQ5VUpB
        SHQrM0VJWFZZNk1oaldIRjFKMEY1M0kKLS0tIEhFejRLNm9wcnFwOE91LzRaeUxU
        UWRqVTBLS0JGV0c4TXhBaXZZOVUxU2MKG9WnIGa5K51ab4t4r9arCuHRI/hsnUck
        YKpaKzYWYXHg8LpHnDHqT1izBldGK28p3b6N+wdp6bLIuVa3n7kPEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T03:34:50Z"
  mac: ENC[AES256_GCM,data:RLV3l40CHn2aNtccYKTuHADxNhC9ZHJhfIdfDtlpfLr47S2KPWHYiwT2McAdSaGgwGnKa1nXvvOXKhy15+FceGxktB71Ca1VThVmd3arfwlmt58CWroxJJ4TqfoGjNmxPfOZwTeUPb14oGOYh6qh58omwn2m8FXdffIRKVL0nhE=,iv:5ymNhymTrgHT2Qpc5UiO9WVTMcD/iylPtQgpCuEppUo=,tag:AoD/AiPJC58Ixy0Sn6UJog==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
