apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pcab
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: kubernetes
  sources:
    - repoURL: https://github.com/mebezac/home-cluster.git
      path: kubernetes/apps/pcab/pcab
      targetRevision: main
      ref: pcab-repo
    - repoURL: ghcr.io/bjw-s-labs/helm
      chart: app-template
      targetRevision: 4.6.2
      helm:
        releaseName: pcab
        valueFiles:
          - $pcab-repo/kubernetes/apps/pcab/pcab/values.yaml
  destination:
    name: in-cluster
    namespace: pcab
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
