apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: n8n
stringData:
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:N9f7MQ3VV1eMwLZePqjtbCvmcU+YcMXHuLG8YtGFJhmpJEEW6p8B9Ly/G19yTQo6/Q==,iv:d5UUvePd6eWd8EvG4o4oO78UXab/QZ84oMNpp/9SMMI=,tag:mIL2HHiCYp3KA2HlZVcFEw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:n2na3Ad+VEw4pL7Vby6CS5zaAZLH9dm1dmI=,iv:DzP3GjLE5CCS4FTuAISsH2I9artSq0TC+zFLvMyqaqc=,tag:fPtF3e/9xSe2lkUMBBZKjQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:WhMw,iv:wVbXeXEmINvBEdCG/TH148TehTX399tb1RbXYNyAXXs=,tag:hBvf9aUhiTYGBJnzFOWwdw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:0cAb,iv:5dIt4intHu6GuqFUqHcfQV10Z/maN9sovfaVbiFR6Ck=,tag:Q75AmQi0vPqyHRPhJb5HMw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Fihgh5Q4Yei0PjwUqbnyWJsMdoI2tQ0=,iv:SI7ZzqIPfPhe90kILenWCqzq2DnhmABj5V5orBI+pYQ=,tag:Z+CKtt82+SSyox8m58O3mA==,type:str]
  #ENC[AES256_GCM,data:9FLDCWMmz7N3,iv:hkYJnF6lPOKZH24FqBrSJ3ZeRIxeKzuLczx3STJKC1k=,tag:8BPSnPU5onOe7j7nGZU/kw==,type:comment]
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:eamQ6Kw2qy9PTAnpbGtJ3G8J//C8h0IaAYxvMasMLepfeO2bcHFceBt8rPzUHXXj3q+zy4ZoNRChWGGYSz48GA==,iv:RiWf4vW7beOgqHjRd6AQqq96rxnRMnyj+eIACTf+PpE=,tag:pRmfX7ih3zFWWnaa8zz0MQ==,type:str]
  DB_POSTGRESDB_HOST: ENC[AES256_GCM,data:IzeeW6mY1bKg9odrToiYR8s+oHBXLiMMQN9PIdV29yKyEEfhJ3zVPT3H/WD5YJMqEA==,iv:jnEGI81oQRNijZMKNy0imRqJ5A/UT/iW6i3029qMUgQ=,tag:Sa+VRNftCEgV67QLKJRejQ==,type:str]
  DB_POSTGRESDB_PORT: ENC[AES256_GCM,data:0O1IvA==,iv:4eJoh6TJMVJj/5Yt8k/2KaLOy09ehjrVk0HIE+niN0g=,tag:GK3VDXmPfBJY4nVOsKjbtA==,type:str]
  DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:uRoi,iv:XeVC8XDN1Gbb3o4ziRPvpr0ljwn0axrm9U9H6gBR2C8=,tag:YA5rNYMgkz/82YfKrHe2fg==,type:str]
  DB_POSTGRESDB_USER: ENC[AES256_GCM,data:RzXz,iv:HpCWlVUOawPo7+kZsadEdxeKrrhi7N4NygcIQouji6k=,tag:0DiPpZFsHpN8BkDn/ER/KA==,type:str]
  DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:gUTN7NLT2fLLnf2a/Vid4QCnduZ6Z1U=,iv:OP/fLMMok7Fw5/iUVMKZO1oWCIhw9+L5fPcPGsPHkIo=,tag:YNYc950mZN137tvTs4e5aw==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNDlzemtZQ09YMTIrN01V
        dFdNdzY0YWs3TUE3YW8waDJkcy92WVV4NVhnClpoU3lSZ0tzQkRrY1VsWkRjR0ZX
        UlpHd3MxOG80eHB3dlllOWFJMWp0dzAKLS0tIFR0S0hTUGllL0h5T0tZK2NOcmtN
        clRQQlp2eWVlZDBkZkVOVmVzT2xCYmsKFwetqnKZi7hYX3YtQVH1JrzvstnTvJtY
        6Reqmu14EnLMWaZ/71DJJ6gsM1/PHjihuL9hes6VdaMD0plS6oX9ZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T15:32:10Z"
  mac: ENC[AES256_GCM,data:IPJGArOQnvOjLx1G8adJa/9aeLtrmdAbzu/T9O/f4w1+0NFHv7htXWALTKsDO3FFMT3E57IF5BRQi7axwoGfOGqK73LRd0rUlyFOe7a3FrycSJDbXXiwihMo9SviJygyjlLA1cybecte4mUu7olbhK6ShyHWFqXHTmphK/1otaY=,iv:1M97EBRmEH8aTd8fZZiEmPGpslJ3ox4/+0ZmRw7Xoxg=,tag:Oq9AG8nKhNd060itNGRceQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
