apiVersion: v1
kind: Secret
metadata:
  name: podcast-adblock-secret
  namespace: podcasts
type: Opaque
stringData:
  REQUIRE_AUTH: ENC[AES256_GCM,data:ipmCTQ==,iv:f2apXbXu0/LDRmoqqvswZdLg4eVXcDSOhoorcD5lx0g=,tag:keLN9mGSnPJ10D1a4UekbA==,type:str]
  PODLY_ADMIN_USERNAME: ENC[AES256_GCM,data:fgrM,iv:MiweJBFgaRf2V5HwEd61mMnJJ/tRY/SeSKs6XgWvS8A=,tag:yVMwQ3V1LmmxsunWC9s8fQ==,type:str]
  PODLY_ADMIN_PASSWORD: ENC[AES256_GCM,data:GcgyK1poY2J50YmfPr7/MA3Kx30auKiSpg==,iv:6wj8MtIgZ9JtGSjsn9wG1mVvxWTIl6XretwmpHQb5/c=,tag:W2V+cyN0XP2Ov8fc7jYQzw==,type:str]
  PODLY_SECRET_KEY: ENC[AES256_GCM,data:f2vUDpfKZAVDMmqN+I6+596iKR4FZRuPyRXKlMQYS+sUM1Xdwp6oXrwoMxndn+MUjn87KlxcpKMC3VIylVY31A==,iv:jJNyv8XOPxXg6vGAk4hYBu5CIGnr8pkSjZpOzaMicNc=,tag:oO78OdvPi/eqkh56PO/6+w==,type:str]
  GROQ_API_KEY: ENC[AES256_GCM,data:lksptiut8NBOppvPXs1Dg5Eu38Fs24g1RC81iKifXfS2obF/wzZ4G1AlwPHCsqdk29RgIllYUYU=,iv:PfBFLcYBvHbaZfjRx1POHLKvHkPXIPO8didAe6aFt+s=,tag:mLcXw9+kSnIaGFyqhU14OQ==,type:str]
  LLM_API_KEY: ENC[AES256_GCM,data:tqaPAVzoJ5tNZGRZgYsZr+ficBdjyFXROtmwyKOEohLfyr5AY2001n0qDN7RTqbhj5P0s2L/VbqGNp6Y4dTsfpNibbf5XI/0eQ==,iv:bTo/muCwP/jn8TYBgJG3ozGVXGAyYzcQWKIc0yyjNqw=,tag:un8Ee8XYEyigDy5xwSCaAA==,type:str]
  LLM_MODEL: ENC[AES256_GCM,data:ZXHGPOU25rde/vaJD0W9mZl4JyXB7wHqfiZjp+TQI/0+JTCaG9z2CB6UhnI6,iv:CZ2L9g9rfBs7zmMBbcM9t/pdmRPnNGPq3E7cWkVUhz4=,tag:9Pug6eb+wnlISuUKBqp3Ww==,type:str]
  OPENAI_BASE_URL: ENC[AES256_GCM,data:8eS8eYzxlki5y6i3RY5pekGf8o2Nmiu6lkHuVg==,iv:C1/hYCAckM8HaL1FK6IdbcqWKLOWL/neCv9G9Zk1/BU=,tag:Epnlx2tQLZEsin2tnyMLGw==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbllPSG5rODJQVnNNWVRj
        QjdqTlRYTEpINTBsR3BmdkJZYkFJejI3QWowCkxYaEQrdXAxdHRxd3FaZE1EeVZj
        alZWZW9TeUVHQWxkK3pCNTA2bGk3Yk0KLS0tIGV3cGswcE5pVG1xaWNBZHNuckZH
        K0JKYUQwdnJGMFhnQWRHMGxiR0pkbkEKIXwx7uNvzhSGw9OIZhcrp7MFozUG7473
        w0y/QXwHcbU87Axhbqlri4S50c9phhOkgxXtA48MxS6Y88iXLMbONQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T03:41:29Z"
  mac: ENC[AES256_GCM,data:eex8KstekZEw9nroRfoE+BJ9fvNIHqYcO88W88F/kgrJX1/htgWz+HfaLFRwCqSL2ImO7B6ksxd1jtoDYAKtABMxSY/c5AJFlBXSGjdcN+P9GFL755lnh9e5T44s/WfH67eU3V8dT3L2r9CgPHyAUg/g5KeF5B5f+SOTqyVcRTc=,iv:opaVIKqJtLItricTEbGpqZcCb13YKjUyfUEzBBlRMVo=,tag:xEP6JW4InGOt0sehB2QstA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
