# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:yuLI1Nyzcb4Ceqj3KaIseUUGelKtE3njV1qMbOv/ESjh5njt6Y3yEw==,iv:IOgJkZ2AhV010BfIPy5XL8kJ3bWZLk0xYEtlfGn+i54=,tag:GhMhoNAjlURozQquK3/TBw==,type:str]
  biglink-party-api-token: ENC[AES256_GCM,data:s0wbPMlh1GqnJtt0ehIThZsJpz0k3JipIfcB1h5QkmlGg/syRMNvxg==,iv:4sm/Fdy8yFqHnPcWIJNsyFhQOrhEFTdQ3tWn9owb7Fw=,tag:8oQt6UbrNiRgQGNrj6A9vw==,type:str]
  zac-pizza-api-token: ENC[AES256_GCM,data:zWzvy3xlSnLp5aeXkmOl3OK2M4zA7+3RiJKDFq72KbiIgCaLsi1PGg==,iv:Sdc/JmNZKHtQ6J7T6HkjqOFDj4HMzUZSqc5Svu8Tr/c=,tag:v6h4mvskVmKi+JS5dxbaRg==,type:str]
  heremag-free-api-token: ENC[AES256_GCM,data:4w4DleGUbEz4sx0rDHRlvlQFy8xXWJ5p2Uv/r9j/fK7f6l270W9Lhg==,iv:Tx56KOp7/JGsZrE0KZHN7b4WFVzCehyQFERaT2I5+V8=,tag:IprEKJR0RclyYglxiLf6Kw==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWW5YcXVwZ1EyTUpoTGtU
        Q25vSXJvWlFUV2swdXVYVnJDTm5MRTY1V0NFCi9VR2FZZlQ5V0h1NVRyZzJ2Qkpy
        K3hjSXRQVXUxcEcyQ1Rza1hLRERWTlkKLS0tIE1GaEdDSWdJUFg4K3RxZnU3aHlV
        aW91M3ZSUVVRU1p2ZTR4VXhqRUIreFkKqLx27PMxtQzfPCnM5dBNVU/Xs7DGJiE3
        qfOXxtyE3EPG+nD3iQXcczvwMKu0DXjfwkQrT0o7ZR/142AFeE1Feg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T02:37:21Z"
  mac: ENC[AES256_GCM,data:pyqJ12Ak/n84uQOokbtGYIYTQ9/PORRwskOv9jtw/OFUiWCqJuX5U/ZnA0suxVQesnLpF/WkbZgMUYHKjDMjKOdux/5/sxOrBCOFUdoc80HTlYIoqdp1ity+VkktkKDnm1jiVr1gHuAhKeAnvBVLQoiiT0b/MEnnIJ4XIU3a5JY=,iv:4Vt2ZDJ/eOsyTdkYwRTJZw30WkcnRlHgR7ccSQbLENE=,tag:3cZITgK6bDx6SKsCfc6ISA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
