apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-stack
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: kubernetes
  sources:
    - repoURL: https://github.com/mebezac/home-cluster.git
      path: kubernetes/apps/observability/victoria-metrics-stack
      targetRevision: main
      ref: victoria-metrics-repo
    - repoURL: https://victoriametrics.github.io/helm-charts
      chart: victoria-metrics-k8s-stack
      targetRevision: 0.72.1
      helm:
        releaseName: victoria-metrics-stack
        valueFiles:
          - $victoria-metrics-repo/kubernetes/apps/observability/victoria-metrics-stack/values.yaml
  destination:
    name: in-cluster
    namespace: observability
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: victoria-metrics-stack-victoria-metrics-operator-admission
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    - kind: Secret
      name: victoria-metrics-stack-victoria-metrics-operator-validation
      namespace: observability
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
