apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-logs-collector
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: kubernetes
  sources:
    - repoURL: https://github.com/mebezac/home-cluster.git
      path: kubernetes/apps/observability/victoria-logs-collector
      targetRevision: main
      ref: victoria-logs-collector-repo
    - repoURL: https://victoriametrics.github.io/helm-charts
      chart: victoria-logs-collector
      targetRevision: 0.2.11
      helm:
        releaseName: victoria-logs-collector
        valueFiles:
          - $victoria-logs-collector-repo/kubernetes/apps/observability/victoria-logs-collector/values.yaml
  destination:
    name: in-cluster
    namespace: observability
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
