apiVersion: v1
kind: Secret
metadata:
  name: lubelog-secret
  namespace: lubelog
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:5+7/xNfWQA==,iv:CHbAPZK8djS6F0cZXamuZfX50xfFmNzyd6xShCB4kfQ=,tag:3jr8IdK9VWPI6Y+Zs6Ml+Q==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:tufyLOuvxFTgEwG9J9olBtVQHoWarbxPQN2JCesiwsCOOY+deKv2HuTc0ZCPkoatMQ==,iv:oT/eUAz7yMVzFf/dy5hOT5RkUCyUn/6G5wbrxQEl/Xs=,tag:WcqW71jX93VL2ePGKgiZtA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:CvlgapDr0Q==,iv:m+utp23k/LpieYVlpWnMCwLMuHWi/WYqFOT+dOJ4IVw=,tag:TGTXodjbpeZ8NTAgGsYuKQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:cbJcTep81juYIiPC0m4uVQoq/BJPU9Caveg43ws=,iv:5YUYW9OG1F6enbkw56qNqoZvHxCaBxjkerq0kfuoFBM=,tag:ifAxffwJpGQoEsSwPyP+Sg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:usPMgP7nQOBPp/uez9I+pb9reciqcYnf3fM=,iv:drVmSn+tqti4iG9LYqYQ2OqhVF0sMxrepPhah8LjXS0=,tag:oitr2ixoLybI9wvyjE00ig==,type:str]
  POSTGRES_CONNECTION: ENC[AES256_GCM,data:/q3Unh44hUwcs62ptQ2uFXWx1f/NHwd/mRJlIowgG2OMR2srNpZgL8KXQK5uMvVmmuixT/gVanMJ2BfDx5jKaUVbZIGduwHfRQwGU/nhxjKAjodftgNM52OWeLetdg/8ImwtmvqHSjAoC488a65VShxXIVQ9NvZCCxf+GrPJ9EqY9g==,iv:qTyYfDegcAQU2PpKWKNl4gTf9PcUqbIFOqEeOosE8mE=,tag:97SpF77vwTwSM9i7lUExlQ==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTEFsNStiTjlybHpHanN6
        NzVjUTBkM2htSUJRZUd1cXZQMWJEU3dzOFVFCm9JRXBuL2UxSEQ2TkcwRTQ5VUpB
        SHQrM0VJWFZZNk1oaldIRjFKMEY1M0kKLS0tIEhFejRLNm9wcnFwOE91LzRaeUxU
        UWRqVTBLS0JGV0c4TXhBaXZZOVUxU2MKG9WnIGa5K51ab4t4r9arCuHRI/hsnUck
        YKpaKzYWYXHg8LpHnDHqT1izBldGK28p3b6N+wdp6bLIuVa3n7kPEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T22:50:18Z"
  mac: ENC[AES256_GCM,data:Ct/Wvo/4ENwMX+vxX/VYI7IP7CGKDFdCl3lFeKp0QS41re9hW9LUlkr70VPP64NQ5TPrE3vzlHD4tdScUEuGKyXm6874fP8xdKYr9BIbBaM/Fo+ALW8+V+NvHl1FiAXibeknxbcwLQe8ZrG4WZH5rxAqenPqaJkurX0RRsC6JYY=,iv:Gc7r3wUXmudmJvlvSdYnNoL+KaDntwnfz2o5JXKst3Q=,tag:OWeJ+QFW9W6OGJhlVoWSHg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
