apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: heremag-free-production
spec:
  secretName: heremag-free-production-tls
  issuerRef:
    name: letsencrypt-production-heremag-free
    kind: ClusterIssuer
  commonName: heremag.free
  dnsNames:
    - heremag.free
    - '*.heremag.free'
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: heremag
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: heremag
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMjVxcDU3UjIzd2U3MzNZ
        Nkc5c0xyZmxMVGV3eTZiK1JHeEh6blVxNEJjCmQ4bkJMOWFRYVE2a2lEV1YzdHNj
        b0hEVml5clhLY1lPSy9iNmNxaHJzUHMKLS0tIGlZRFJ0bW95bG1IdkpGWG9KbnVK
        N0pONHBPTVd1SUxRZVZvcFFQNEo3YmsKrfvsQxw1xzX8lcYNjH6aN8XOybQhHiyf
        oQZg63IuXrooeHyUJMEufczVcqq+xQkq6r3VLcs5w1kCowJYv3XvDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T21:07:05Z"
  mac: ENC[AES256_GCM,data:cKdwOcVniQhJYmHP/tXRDO2H05ThXDjVYII3bYkoY6kblxpsuP8AlrIkm1yiN87H36hMnDwuFXYRCuzvHkRYa9PHsBgzUF3jhaIcwHxf1iNCER6vgEZuK5lx2ev5AcBRrzkZWjIjFTZYbxu58/EukhTAi6Ft4Lz90FnNpp4GFl0=,iv:0yqfgn/rb17t2Fj1VJY4ucTtLxX/1wIxvaKEqigrrVU=,tag:TKGUUVL9OTQUBoUO+JxpPg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
