apiVersion: v1
kind: Secret
metadata:
  name: jotty-secret
  namespace: jotty
stringData:
  HTTPS: ENC[AES256_GCM,data:OODC6w==,iv:MkcTe+02TeZkzfwwVgCiZMGwHl0VJgiUnA7lnNimPBo=,tag:riwIKEXdo1VN2NZrsoxxrQ==,type:str]
  SSO_MODE: ENC[AES256_GCM,data:4AeefQ==,iv:hU9FIylpYoOZ+SAzp6d1PMvxfZvOalE0NuQs5u6UFfA=,tag:d3c1eB/VF4XoI0SAbXx0VQ==,type:str]
  OIDC_ISSUER: ENC[AES256_GCM,data:OipvtZBpWwFbC/AwvOg6dna8jeMFVxktPJzarVQ=,iv:SAJjc2NbIa91oak71GxwU2yw/4wat3rQjCFgIHmovPo=,tag:Z5iztOFe1QNDszUkoKwSqw==,type:str]
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:Y73gcJlj2B4Ohphm4OnTlbd5UyTpwAPxIHpuVStDk0XQbvNZW8gOE5gRRSV4YXS2w0Llx2k0LN0toEMz6RNvLTIC3oM62LEI,iv:zINS6RsU2JRohR91gJgwiQ5F5iO0ZOOCzULuQbJ4Eys=,tag:bKWpzkqFpSelXaAhyRk36A==,type:str]
  SSO_FALLBACK_LOCAL: ENC[AES256_GCM,data:LSo=,iv:iXTndNec5QGAnKPyBZwiQnfN6WbZcCEB6demwx9Nzl8=,tag:oJCA/gl0v3gFM6bG1BWakA==,type:str]
  OIDC_ADMIN_GROUPS: ENC[AES256_GCM,data:/CDymJVXa911tqE=,iv:nyjryz80smRWBD7ziD+v3K0sKispClMXYZMm1G2DS8s=,tag:TeXxkalVWJHr68tqfkHvTQ==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bVVHa3hDZ0R4TDFGTkNo
        Z1pNNlZnc21PZTF5dnptTWRzUUpBVWlQR0Z3ClA4T010dDVueldKRkFNYjdTUzVO
        SGZDeFJPK1QxODNOU0NKMnUweVFLbU0KLS0tIFhGbGppcExRaWQyNFYreS9aRjQy
        WnlTNUFaU2JVTS9WOHRTT0pkeXUxRE0KYWs7ZhhXBxtK6VKjV2gLKpl74sUQlPXu
        Pvqmp0AWlDb9FRsvLJ3TMIMHc0j9Suv652J+mMaHOoYW/yJoHvyj+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-15T21:58:52Z"
  mac: ENC[AES256_GCM,data:Opb4GanxBk6ttcERwEtTbafPJ7SsWpG5QSLj/eNPk0QrHHrEzW/V/7fJjEGd0xvyzl7OYj0/zK1cVGjaTDyPx8VnQXKrX5D4q4Zf82f7O9IOMn3qO/dZHtdg/1E4ZV71f17Ph7tON41BEDvN7mKyYoCicBBuBHvCOzlADT4nM6E=,iv:ld103c7bNAarQ0v74LbNkemTMscqnGTyaMU1Dh8W5hk=,tag:bIRY9wl5dNtfJkhydwlaBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
