apiVersion: v1
kind: Secret
metadata:
  name: formbricks-secret
  namespace: heremag
stringData:
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:/wxPrwvbFpkYYA==,iv:1jgaHVyPaTFYUnwDQP+ZCTYlchnP9aQO6ieJSEC3QEo=,tag:xoQZVu5cnbWIn8Isbgrh9g==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:tufyLOuvxFTgEwG9J9olBtVQHoWarbxPQN2JCesiwsCOOY+deKv2HuTc0ZCPkoatMQ==,iv:oT/eUAz7yMVzFf/dy5hOT5RkUCyUn/6G5wbrxQEl/Xs=,tag:WcqW71jX93VL2ePGKgiZtA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:Q79o2qkCbLlrgw==,iv:tYQA2lhlCOnyN96Io/K6E7ZbrOUKNxy8ldZ3skLMj8I=,tag:sxVBWR8RDSxMy4zAQvceCQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:p3uaMOwb46I6XC+JsK0yW7Yo2UC+7DgAMYY=,iv:1WOyaP04Rx+IgXouHpMfeZiC9rDGmlG/cgw9DRp1ia0=,tag:Sg9NPrdLDaRLlkpFgRhzpA==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:usPMgP7nQOBPp/uez9I+pb9reciqcYnf3fM=,iv:drVmSn+tqti4iG9LYqYQ2OqhVF0sMxrepPhah8LjXS0=,tag:oitr2ixoLybI9wvyjE00ig==,type:str]
  #ENC[AES256_GCM,data:RsANI/1d1iOl570=,iv:7e9VsmxlGFlIiAr/boKJmhEWKjzy+DlGai6U7GcWfMo=,tag:pdctVzw7wVp+03BrWzKloA==,type:comment]
  WEBAPP_URL: ENC[AES256_GCM,data:gghs9q/p3ZOvdGEJp1wxsC+HUD6rE+rOBMU=,iv:4zdybS4okB3gPKORswf2qkUR4iTdbVznQM7nsN7PWPE=,tag:iFnAzYGJ/T+mz7XKsVUdsA==,type:str]
  NEXTAUTH_URL: ENC[AES256_GCM,data:D7Tidf2bSDrFQatT0E2LF+FO1DI71ay9p4M=,iv:bBwvJqlRYH3YqDi6yO5mCMKA6ymTofwZIIjb0HfymTw=,tag:UFLs9wm+fKnzUvdKFhOVdw==,type:str]
  NEXTAUTH_SECRET: ENC[AES256_GCM,data:aHmxPWA+QrnyusMwg5uJNA7GKec+Dra+oztsdcJScd4QNY06y1jro7ZASlKhY06bUen/ctD5o41W6HHvUnL0tg==,iv:JKlLg2txz5i0QUWN7cbPHGzeFNtN3Lvxv7ceGkkTiWo=,tag:1dkBLO8Pi/X6j8W9QG6t8g==,type:str]
  ENCRYPTION_KEY: ENC[AES256_GCM,data:/FuW+F8xSz8Mid5/KsdIjfqkS0PMWhNEhITKT/aIjkZE6f1/LnkEgOxO+xhteaBPB14F+uJaZLnxdq4kxWaS3A==,iv:hFg+wW058CZWr1Z/bZQinIfRGnoB8HcCp+FkgKs9iXc=,tag:2kqR4L54VMZOgFPW+xzqTw==,type:str]
  CRON_SECRET: ENC[AES256_GCM,data:dIcjue83Gz8v/TrfI/orP+SKl/rpQB6JOS+1ImXdfVXvWcl3fAGF+x/tSD1bKiFsurLN/TukCt3Ql4E6zFVtww==,iv:gqHftXoODRFj9cgmV+/PKTWCacW5i7/xPIZCV3w8Z1w=,tag:6a0lzQZRCWG+1/reOlavpw==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:POOC60bhc8fQ7neFeqIi3DUsyE3SV1nA8m2HqOB1SbJ2hh4xMzMnhd1IwhmSL4y8SDQ/6PzZq+Ik28po6RP0Tytsmy4XUfBWJw==,iv:RG/2bnnOpIZeBEwV0IMOHC7f9UoQp3swfljyGfdKJY8=,tag:UQ4AjrW6YpkF7ie9zxqFuw==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:lUs+wnkhEMW/T8p3oKSloPDc/S8DiTRLx3pMq3CmLAqdus0Bu4rC+2Ltplmf+vOq5nqKQge0T1/CByLQmw9+llUFf1AGQGhliSQnn4vF3xW/YR7erg3TJGb7/ZsHJYboXb/907VQpLbpIf8OBbZK86Ljb47xvCPYbOxhBSkLNWDYkg==,iv:F5drn+GFxFh7pOd+qpjvql10AwaLkFRzvhSnVR2kCsA=,tag:4fbUJpZJfV4W/TwGm86ztA==,type:str]
  S3_ACCESS_KEY: ENC[AES256_GCM,data:U68u3DkSaQ8SQYgEub2FsI+jhvtnUFPh2qg=,iv:0+INHlxkULZhP/SPM+3COG7AwSsv4VCo1G7isOwDaDs=,tag:4M3MoebQlMij6Gc+6BWmMA==,type:str]
  S3_SECRET_KEY: ENC[AES256_GCM,data:BEI9bsYpmPgC5NKbFL0AuANbUboWYIW9Cc+NHjJn/BOBvNc6BgGREKVvIbZVYfZrIz3M1p1a+Gs/cSRqP+VwEQ==,iv:fsdWngNMtFVF+4QMXUs3UpIP4uzjUrknR/WIyuiRfEo=,tag:qEdtWN4X/1XkfQYFNWvS/g==,type:str]
  S3_REGION: ENC[AES256_GCM,data:VhiOaUkRe26L,iv:zCFBE4nsnx5stF89o6uQLtkXPk+FBN12sJzSGfEqPV0=,tag:ThQ/Nad38AmnDMjJgy/2DQ==,type:str]
  S3_BUCKET_NAME: ENC[AES256_GCM,data:PAUl7QPnbeiu+EQlh0g8HRdS,iv:geOmIB5icSDvrwlUxviXs/Rw47jPHiO/9BASL/gaNiM=,tag:0Fs60w+DxqX7ZvNxEEWHEQ==,type:str]
  S3_ENDPOINT_URL: ENC[AES256_GCM,data:3gfqWzKDVyazVeB2yLqel+2VtrtP7MJr/Q==,iv:ljfwPUBvE7AlymJ9yszNPfGuYQoAmzt7+qILJyBe+VQ=,tag:66mC0nYAtv8wg0tyP7gmiQ==,type:str]
  S3_FORCE_PATH_STYLE: ENC[AES256_GCM,data:DQ==,iv:+lT9O12l1Po1+M0Ik+m345S+lPXPH6FYHXP4bU9Bb7A=,tag:pXI2fFCgLiNHV1939w3LYQ==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTEFsNStiTjlybHpHanN6
        NzVjUTBkM2htSUJRZUd1cXZQMWJEU3dzOFVFCm9JRXBuL2UxSEQ2TkcwRTQ5VUpB
        SHQrM0VJWFZZNk1oaldIRjFKMEY1M0kKLS0tIEhFejRLNm9wcnFwOE91LzRaeUxU
        UWRqVTBLS0JGV0c4TXhBaXZZOVUxU2MKG9WnIGa5K51ab4t4r9arCuHRI/hsnUck
        YKpaKzYWYXHg8LpHnDHqT1izBldGK28p3b6N+wdp6bLIuVa3n7kPEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T22:46:42Z"
  mac: ENC[AES256_GCM,data:QyoDJ5MSD1tXEtsQp9oFI1LCxCQLPYokMOwFXJSW8zkLFFfMrziC85h+3hieQfX3L+N6ogUVmmkV6ZM4bkeJlGspeXvK2967s1oVaw8X6ku5LJ7iJHpPcHz6eKBQzvfLjwQyVqHqT7W4H75v3sSJ6dhNuk4wQ3254HQawG85Wiw=,iv:fwjnOJC0yrvpAAkRcCY7zmJ5RKt19xGR9H3VKm2POzs=,tag:eGlHNbWKHRhhxwJBwWnnJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
