apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: opencode-manager
type: Opaque
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:/R+HAPk5KSE=,iv:tYzt0hq2m0Ak5OzcXhsnzviENCPLxep3pap9fgFptKg=,tag:360ZoVyEu0p68cOv46Sq2w==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:PEztoACoHZ3GGGXM95ZVwa7xKnAmcfgTgC7w,iv:hFi7TXjw4f8BNwXSO+sk5ioV0tMSscjNvi+FVTmP19M=,tag:PESS7uLztmNsOzzRTo9VQg==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwclhQZjFzcEpTM0N0Q212
        dUw3dllNZUlCSEN4RWJLNmg5K2E4NEtraFZvCmdjZFhBTTJ1OFNMVzR6UGdwdHVn
        SFNxcWpKaDZpdVFGY241VHBqM1NTbzgKLS0tIEtvVS8wRnFlT0w3NEdJUUx4Zzdi
        bUFBY3JiaUhrVFVOM1c4K2lqQy82eVEKa+PhQSIxYkncnQTXttvknTgU4piJQr2j
        IIDvxnHFf9rP8M4m90VxEQFMUx/ko3sscKhG6vXyqz+ZCcae1pIWGw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-27T00:55:09Z"
  mac: ENC[AES256_GCM,data:PRk141mILYjPdcN70hspWssE6TqDIGxAJZAXZCN3zQWyNxTH1Q4zjWCUdlH2v7ad3PCsU5pSf0rZBT/1hhFbHcDf0uoLoGT6z4q8+qTcWIEV1Ad2Hm5JIycpJ8lH/PDWp1TnADoyBwnelgypnRurlcSoCQzbzxqUs9dn4EJtdsw=,iv:ZPK64viPmFl4GtldWX5RPSdoWDL+UtEe7PSpvPoerEM=,tag:yHdI2U1PjlI4NlcvXdnzDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
