apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-heremag-free-secret
  namespace: network
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:5AkyXkG3hGX7ZebSfJk8uMWmeffo0AA1zT2WxMNp8P3r9jTu,iv:+RkxdJxuBWmXEwzhcnXFBog1tx7vjWgRMqyS1k2OcHA=,tag:6YQTBxHWm+8k3RmSZKu2rA==,type:str]
  credentials.json: ENC[AES256_GCM,data:A2JcGMz7KkyDylkE4UUY1Kbnr2g8rJrSgLdtmAEoLyF6KhmdqFDI1PHinEBDjeErvkfQZIm/vZLjHI0qVnLzBBeITjYz2uqsGfPEsTSYR90r5ySdRHjHwcE2J7fR7bQ5eR/8T6D2pq4fLOHtTLHF7I70pXxTOwvSpKHXI8U9+tCRbA89mUu3rNL8oBnm7rR8wzQQAi9+YdUgZ5OZAJkY3Tq9qDRlFPXCWrwgfA==,iv:/G+2umlSax3Z8WmTQBHMjVt06Sq8snlOvx7XKyavnBE=,tag:04KSOv3ML0+B9VJUPA+I9A==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UE1MV0ZhMVY2WWhmMnBR
        K0p4WlRhOUtBSnVTb0FmbFR2OXd6V0hVT1NvCis2dkc1QTZ0bE9KZUo2WnJaalVK
        MHRWQVNRaHZ3d3luNzhjbU5iY3c1YVEKLS0tIHkxa1d0UWdrNjYrMTRMeXd0U1g3
        Y3dTQjlJN1g1L05ZbWtMcnQvMmluNmcKpVAPQIgXAOQyjwEEzo01c/zx8F88b5o2
        TOtDEvS2gPEO6kBFm1rvhqZoGWTf6AfSiNb9MYYvJ8vt+g5y6YxVYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T14:57:17Z"
  mac: ENC[AES256_GCM,data:PtJ+iuWmgJuA7JG2gQJrz/6LL/NLae3cnjmZ8Y/2T6Vx68aryC7FHzuo9WfBZSrFpDqfQ6eawvEwUInrdkJF+LhEyhB0ULo8hVHDb314xA/L/DK5JMkvb9L5PfYT4d774WYBmpdceBtEuMPkkovmFPhJbNj2/99Ql+ysC7icQ4k=,iv:hr/FdEVjQw1ExIwZiz9okVqUkGwgre43IZJJstDYR+s=,tag:Iatzv32MOqRHBAFgrzYNYg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
