---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plugin-barman-cloud
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: kubernetes
  sources:
    - repoURL: https://github.com/mebezac/home-cluster.git
      path: kubernetes/apps/database/plugin-barman-cloud
      targetRevision: main
      ref: plugin-barman-cloud-repo
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: plugin-barman-cloud
      targetRevision: 0.5.0
      helm:
        releaseName: cloudnative-pg
        valueFiles:
          - $plugin-barman-cloud-repo/kubernetes/apps/database/plugin-barman-cloud/values.yaml
  destination:
    name: in-cluster
    namespace: database
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
