apiVersion: v1
kind: Secret
metadata:
  name: tailscale-secret
  namespace: garage
stringData:
  TS_AUTHKEY: ENC[AES256_GCM,data:qe0FcXE7ALv3aXLB93ct156TnBCA84R/84v0ETuS98byt6MR5QjrIVPfDjjeZ/ovmdBfqiSLZ9DQeWHElos=,iv:piRKiAti6uVTV8GOUNMsXxgHzSs4xbjd5PGMeRc09b8=,tag:QR/ORPJCl0fcgVpXq9/34A==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtR3J4Skd1alVQbFlWRU55
        S1M5QzBrcmRXbHRidGJxbkkwam1Wald0VkJVCjl1MzdFeXZGMCtYQ3VYdGZIcnlD
        ZXM1Vkx0blhXMjdYblVEZ3F1U1FpZlUKLS0tIDVVTGJnNDRRRnZkNk94T0sycnd2
        elF3Z1ZNTnhBY3hGRFhVYWRKV09uY2cK3XQecj0NgO8bqbBccq9nIdLCisufeRPE
        hP9IAmBVadoTPYZtdFTKRTypa4XdF4hf/e2NFaCM6VH4ctmQ+huwYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T03:08:26Z"
  mac: ENC[AES256_GCM,data:jE7JtqQEPxB1wJvnIXILrQ9afsRMGG5UsQGIbYPnwKJ4KlRXBlEGaPCkBIS48PsrkpjIqmt7OtiGA5F3UlO5HihGYZLRuf7F3ywyzRUWg8GBX2aBwDclm/903C+wXLA3dH4nCO2LMfaUGV9bvdZ5GbQrA+FziM9gdbTzsaQ+fiw=,iv:xB+ok+YJt4j+VY8eMatLwpHREBPU35v0/PIc7msJSb4=,tag:uIPvaYXguklgA4U0rIBX5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
