apiVersion: v1
kind: Secret
metadata:
  name: tailscale-secret
  namespace: garage
stringData:
  TS_AUTHKEY: ENC[AES256_GCM,data:u12zdGjZCJvBBqvYI82+cWBsgrGm2QW6P0y3zaEbVknSABV6ZvA07Q5EgYWRX4thcitDdEmMRtRY6uXhFg==,iv:EGuA5vZzLuOqDd0bUKUdZ0qDownCGFTQi2b8tsUjcqQ=,tag:MpmOivWy82lmeM7XD1dA0w==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtR3J4Skd1alVQbFlWRU55
        S1M5QzBrcmRXbHRidGJxbkkwam1Wald0VkJVCjl1MzdFeXZGMCtYQ3VYdGZIcnlD
        ZXM1Vkx0blhXMjdYblVEZ3F1U1FpZlUKLS0tIDVVTGJnNDRRRnZkNk94T0sycnd2
        elF3Z1ZNTnhBY3hGRFhVYWRKV09uY2cK3XQecj0NgO8bqbBccq9nIdLCisufeRPE
        hP9IAmBVadoTPYZtdFTKRTypa4XdF4hf/e2NFaCM6VH4ctmQ+huwYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T23:13:24Z"
  mac: ENC[AES256_GCM,data:r/ZVKRqJQOUihqSa1ts4auol2yC9YMFFTo8EqisepVidDQ0Bket0GwL/NiRmrUzZYtY0Ha58J4m7nj3v+XtQNiwOFJKYknscMHknG9icyUpRvLuIL2BKYZUoSL4SpIMcF950Fswf5mjdAe4d8ImjSTPZWOjssRzGfyZiAB0MVFc=,iv:/wen/py7ErE/3sZIp9y11agisVk+JdB7TYSNE/qNvnk=,tag:hyaORMwNTbe/cb3EHpj1yg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
