apiVersion: v1
kind: Secret
metadata:
  name: external-dns-heremag-free-secret
  namespace: network
stringData:
  api-token: ENC[AES256_GCM,data:kbFEx3F++1mdRmxNkpYMTGygneFjV8mCA/CMQKu+Z1Kefiyhm/cLSQ==,iv:N3hgNF5lFAS7Obn6zAgP9RA+ZW2m9+dtzTwBD/4iJNY=,tag:F+yS848c2Z7sB20p8oVjuA==,type:str]
sops:
  age:
    - recipient: age1j7x3jkw82w02taqj8dmqplae07fxcrup2enejnta9z2v82fzsakqd4ka6p
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbURBaTJodDB1cndvSWxY
        aWpmRWZ6MFRISExxbDV5L3Z1UFlkcGJrQm1FCnNMOE1JaGpXWkRQcHNDb1JCZVQ5
        VlI5dyt1WkFCMUIzWXUxTzd6MG1yOVUKLS0tIGFaY1FWQ001eldUc0YxOW1DT2Fp
        Ym03bXYxdVJTU1kvaWJndGNmT2Nnc0kKymEaMDE0Jsc7+sXD9TDuCoNvRR6Sbk2e
        hDfb4vebdQp9rSRNk0B7rkAnTodFqaVfc6FmTXRuFF0BmDVWHzeC1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T02:35:00Z"
  mac: ENC[AES256_GCM,data:AnfvB/mOvkl9XvXUkxNSClwe8hARCR2EZkxFsDxKtcq/RdYvBlDMNsFv5DNLH2AKlCM2xr2xOxfvGZoyo6zt20qS2DmFSMildzefiX9fR6afWJRipPVcClyj6qWv4ht+dxi+mE92BFjVz5WsWNfN7mGl1BClhaHPphgUPaUvWQM=,iv:2sDQOrrarKlJ2DOWnWh0tLEzpw9ES9lNFd3sPlORGyY=,tag:9Myo/p4ckEa+tfN1wgcc7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
